### PR TITLE
fixes an issue where single quote would be considered invalid literal

### LINKED ISSUE #14: Using a template with single quote fails
The follow code

```golang
uriTemplate, err := template.New("{+baseurl}/reports/getActiveUserDetail(period='{period}')")
```

fails with the error

```
errors.errorString{s:"uritemplate:72:invalid literals"}
```

according to

> If the literal character is allowed anywhere in the URI syntax (unreserved / reserved / pct-encoded ), then it is copied directly to the result string.

https://datatracker.ietf.org/doc/html/rfc6570#section-3.1

single quote being a reserved literal in the URI spec, it should be copied as is (and therefore accepted).

After testing the sample template with [a dotnet equivalent library](https://github.com/tavis-software/Tavis.UriTemplates) and a [java equivalent library](https://github.com/hal4j/uritemplate) parses the template properly.

Removing the quotes from the template also results in a successful parsing.

I believe an entry should be added here, but before I submitted any pull request I wanted to get a confirmation on the analysis.

https://github.com/yosida95/uritemplate/blob/fa7d6df706b972aab27d83eb70e9f7df6696cba5/parse.go#L42

### PR DESCRIPTION
**Pull request by baywet**
fixes #14

### CODE REVIEW

**Comment by yosida95** [comment]
The logic part is perfect. However,  the RFC errata has not yet been accepted, and even after it got accepted it wouldn't appear in the main RFC text. Therefore, could you add a link to the errata or the clarification thread above the single quote entry?

**Comment by yosida95** [comment]
The logic part is perfect. However,  the RFC errata has not yet been accepted, and even after it got accepted it wouldn't appear in the main RFC text. Therefore, could you add a link to the errata or the clarification thread above the single quote entry?

**Comment by baywet** [comment]
thanks for the quick review. Added. let me know if you need anything else!

**Review by yosida95 — APPROVED** [review]

**Comment by baywet** [comment]
Thanks for merging! Let me know when the tag is ready!

**Comment by yosida95** [comment]
I just published v3.0.2. Thanks!

**Pull request merged**
